name: Build ecasound with MSYS2
on: [push, pull_request]
jobs:
  build-ecasound:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: >-
            mingw-w64-x86_64-libsamplerate
            mingw-w64-x86_64-libsndfile
      #- name: get JACK2 source code
      #  uses: actions/checkout@v2
      #  with:
      #    repository: jackaudio/jack2
      #    path: jack2
      #- name: waf configure
      #  working-directory: jack2
      #  run: |
      #    ./waf configure \
      #      --prefix=/mingw64 \
      #      --
      #- name: waf build
      #  working-directory: jack2
      #  run: |
      #    ./waf build
      #- name: waf install
      #  working-directory: jack2
      #  run: |
      #    ./waf install
      - name: get Ecasound source code
        shell: bash
        run: |
          git clone https://git.code.sf.net/p/ecasound/code ecasound
          cd ecasound
          git checkout v2_9_3
      - name: autogen
        working-directory: ecasound
        run: |
          ./autogen-vc.sh
      - name: configure
        working-directory: ecasound
        #--disable-largefile     omit support for large files
        #--enable-shared[=PKGS]  build shared libraries [default=yes]
        #--enable-static[=PKGS]  build static libraries [default=yes]
        #--enable-all-static	  Build only static binaries (default = no)
        #--enable-jack \
        run: |
          ./configure \
            --disable-dbc \
            --disable-effects \
            --disable-oss \
            --disable-osstrigger \
            --disable-arts \
            --enable-libsamplerate \
            --disable-pyecasound \
            --disable-rubyecasound \
            --disable-ncurses \
            --disable-audiofile \
            --enable-sndfile \
            --disable-alsa \
            --enable-sys-readline \
            --disable-liboil \
            --disable-liblilv \
            --disable-liblo \
            LIBS=-lws2_32
      - name: make
        working-directory: ecasound
        run: |
          make
      - name: make install
        working-directory: ecasound
        run: |
          make install
